'use strict';

/**
 * @ngdoc service
 * @name fasterScaleApp.behaviorMap
 * @description
 * # behaviorMap
 * Constant in the fasterScaleApp.
 */
angular.module('fasterScaleApp')
    .constant('BehaviorMap', {
        'REST001': 'accepting life on God\'s terms, with trust, grace, mercy, vulnerability and gratitude',
        'REST002': 'no current secrets',
        'REST003': 'working to resolve problems',
        'REST004': 'identifying fears and feelings',
        'REST005': 'keeping commitments to meetings, prayer, family, church, people, goals, and self',
        'REST006': 'being open and honest',
        'REST007': 'increasing in relationships with God and others',
        'REST008': 'true accountability',
        'F001': 'start believing the present circumstances and moving away from trusting God.  Denial, flight, a change in what\'s important.  How you spend your time, energy and thoughts',
        'F002': 'secrets',
        'F003': 'less time/energy for God, meetings, church',
        'F004': 'avoiding support and accountability people',
        'F005': 'superficial conversations',
        'F006': 'sarcasm',
        'F007' : 'isolating',
        'F008' : 'changes in goals',
        'F009' : 'obsessed with relationship',
        'F010' : 'breaking promises and commitments',
        'F011' : 'neglecting family',
        'F012' : 'preoccupation with material things TV computers entertainment',
        'F013' : 'procrastination',
        'F014' : 'lying',
        'F015' : 'over-confidence',
        'F016' : 'bored',
        'F017' : 'hiding money',
        'A001' : 'a growing background noise of undefined fear; getting energy from emotions',
        'A002' : 'worry',
        'A003' : 'using profanity',
        'A004' : 'being fearful',
        'A005' : 'being resentful',
        'A006' : 'replaying old negative thoughts',
        'A007' : 'perfectionism',
        'A008' : 'judging other\'s motives',
        'A009' : 'making goals and lists that you can\'t complete',
        'A010' : 'mind reading',
        'A011' : 'fantasy',
        'A012' : 'co-dependent rescuing',
        'A013' : 'sleep problems',
        'A014' : 'trouble concentrating',
        'A015' : 'seeking/creating drama',
        'A016' : 'gossip',
        'A017' : 'using over the counter medications for pain sleep or weight control',
        'A018' : 'flirting',
        'S001' : 'trying to outrun the anxiety which is usually the first sign of depression',
        'S002' : 'super busy and always in a hurry',
        'S003' : 'finding good reason to justify the work',
        'S004' : 'workaholic',
        'S005' : 'can\'t relax',
        'S006' : 'avoiding slowing down',
        'S007' : 'feeling driven',
        'S008' : 'can\'t turn off thoughts',
        'S009' : 'skipping meals',
        'S010' : 'binge eating (usually at night)',
        'S011' : 'overspending',
        'S012' : 'can\'t identify own feelings/needs',
        'S013' : 'repetitive negative thoughts',
        'S014' : 'irritable',
        'S015' : 'dramatic mood swings',
        'S016' : 'too much caffeine',
        'S017' : 'over exercising',
        'S018' : 'nervousness',
        'S019' : 'difficulty being alone and/or with people',
        'S020' : 'difficulty listening to others',
        'S021' : 'making excuses for having to "do it all"',
        'T001' : 'getting adrenaline high on anger and aggression',
        'T002' : 'procrastination causing crisis in money, work, and relationships',
        'T003' : 'increased sarcasm',
        'T004' : 'black and white (all or nothing) thinking',
        'T005' : 'feeling alone',
        'T006' : 'nobody understands',
        'T007' : 'overreacting',
        'T008' : 'road rage',
        'T009' : 'constant resentments',
        'T010' : 'pushing others away',
        'T011' : 'increasing isolation',
        'T012' : 'blaming',
        'T013' : 'arguing',
        'T014' : 'irrational thinking',
        'T015' : 'can\'t take criticism',
        'T016' : 'defensive',
        'T017' : 'people avoiding you',
        'T018' : 'needing to be right',
        'T019' : 'digestive problems',
        'T020' : 'headaches',
        'T021' : 'obsessive (stuck) thoughts',
        'T022' : 'can\'t forgive',
        'T023' : 'feeling superior',
        'T024' : 'using intimidation',
        'E001' : 'loss of physical and emotional energy',
        'E002' : 'coming off the adrenaline high and the onset of depression',
        'E003' : 'depressed',
        'E004' : 'panicked',
        'E005' : 'confused',
        'E006' : 'hopelessness',
        'E007' : 'sleeping too much or too little',
        'E008' : 'can\'t cope',
        'E009' : 'overwhelmed',
        'E010' : 'crying for "no reason"',
        'E011' : 'can\'t think',
        'E012' : 'forgetful',
        'E013' : 'pessimistic',
        'E014' : 'helpless',
        'E015' : 'tired',
        'E016' : 'numb',
        'E017' : 'wanting to run',
        'E018' : 'constant cravings for old coping behaviors',
        'E019' : 'thinking of using sex drugs or alcohol',
        'E020' : 'seeking old unhealthy people and places',
        'E021' : 'really isolating',
        'E022' : 'people angry with you',
        'E023' : 'self abuse',
        'E024' : 'suicidal thoughts',
        'E025' : 'spontaneous crying',
        'E026' : 'no goals',
        'E027' : 'survival mode',
        'E028' : 'not returning phone calls',
        'E029' : 'missing work',
        'E030' : 'irritability',
        'E031' : 'no appetite',
        'R001' : 'returning to the place you swore you would never go again. Coping with life on your terms.  You sitting in the driver\'s seat instead of God',
        'R002' : 'giving up and giving in',
        'R003' : 'out of control',
        'R004' : 'lost in your addiction',
        'R005' : 'lying to yourself and others',
        'R006' : 'feeling you just can\'t manage without your coping behaviors at least for now.  The result is the reinforcement of shame guilt and condemnation and feelings of abandonment and being alone'
    });
