'use strict';

/**
 * @ngdoc service
 * @name fasterScaleApp.behaviorMap
 * @description
 * # behaviorMap
 * Constant in the fasterScaleApp.
 */
angular.module('fasterScaleApp')
    .constant('BehaviorMap', {
        'REST001': 'Accepting life on God\'s terms, with trust, grace, mercy, vulnerability and gratitude',
        'REST002': 'No current secrets',
        'REST003': 'Working to resolve problems',
        'REST004': 'identifying fears and feelings',
        'REST005': 'keeping commitments to meetings, prayer, family, church, people, goals, and self',
        'REST006': 'being open and honest',
        'REST007': 'increasing in relationships with God and others',
        'REST008': 'true accountability',
        'F001': 'Start believing the present circumstances and moving away from trusting God.  Denial, flight, a change in what\'s important.  How you spend your time, energy and thoughts',
        'F002': 'Secrets',
        'F003': 'Less time/energy for God, meetings, church',
        'F004': 'Avoiding support and accountability people',
        'F005': 'superficial conversations',
        'F006': 'sarcasm',
        'F007' : 'isolating',
        'F008' : 'changes in goals',
        'F009' : 'obsessed with relationship',
        'F010' : 'breaking promises and commitments',
        'F011' : 'neglecting family',
        'F012' : 'preoccupation with material things TV computers entertainment',
        'F013' : 'procrastination',
        'F014' : 'lying',
        'F015' : 'over-confidence',
        'F016' : 'bored',
        'F017' : 'hiding money',
        'A001' : 'a growing background noise of undefined fear; getting energy from emotions',
        'A002' : 'worry',
        'A003' : 'using profanity',
        'A004' : 'being fearful',
        'A005' : 'being resentful',
        'A006' : 'replaying old negative thoughts',
        'A007' : 'perfectionism',
        'A008' : 'judging other\'s motives',
        'A009' : 'making goals and lists that you can\'t complete',
        'A010' : 'mind reading',
        'A011' : 'fantasy',
        'A012' : 'co-dependent rescuing',
        'A013' : 'sleep problems',
        'A014' : 'trouble concentrating',
        'A015' : 'seeking/creating drama',
        'A016' : 'gossip',
        'A017' : 'using over the counter medications for pain sleep or weight control',
        'A018' : 'flirting',
        'S001' : 'Trying to outrun the anxiety which is usually the first sign of depression',
        'T001' : 'Getting adrenaline high on anger and aggression',
        'E001' : 'Loss of physical and emotional energy',
        'E002' : 'Coming off the adrenaline high and the onset of depression',
        'E003' : 'Depressed',
        'E004' : 'Panicked',
        'E005' : 'Confused',
        'E006' : 'Hopelessness',
        'E007' : 'Sleeping too much or too little',
        'E008' : 'Can\'t cope',
        'E009' : 'Overwhelmed',
        'E010' : 'Crying for "no reason"',
        'E011' : 'Can\'t think',
        'E012' : 'Forgetful',
        'E013' : 'Pessimistic',
        'E014' : 'Helpless',
        'E015' : 'Tired',
        'E016' : 'Numb',
        'E017' : 'Wanting to run',
        'E018' : 'Constant cravings for old coping behaviors',
        'E019' : 'Thinking of using sex drugs or alcohol',
        'E020' : 'Seeking old unhealthy people and places',
        'E021' : 'Really isolating',
        'E022' : 'People angry with you',
        'E023' : 'Self abuse',
        'E024' : 'Suicidal thoughts',
        'E025' : 'Spontaneous crying',
        'E026' : 'No goals',
        'E027' : 'Survival mode',
        'E028' : 'Not returning phone calls',
        'E029' : 'Missing work',
        'E030' : 'Irritability',
        'E031' : 'No appetite',
        'R001' : 'Returning to the place you swore you would never go again. Coping with life on your terms.  You sitting in the driver\'s seat instead of God',
        'R002' : 'Giving up and giving in',
        'R003' : 'Out of control',
        'R004' : 'Lost in your addiction',
        'R005' : 'Lying to yourself and others',
        'R006' : 'Feeling you just can\'t manage without your coping behaviors at least for now.  The result is the reinforcement of shame guilt and condemnation and feelings of abandonment and being alone'
    });
